## Lesson 47 Practice Project: Urban Insights – Data Analysis of Park Distribution in San Francisco

In [13]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency, pearsonr, spearmanr

df = pd.read_csv('sf_parks.csv')
df.head()

     neighborhood  num_parks  pop_density  avg_income
0  Neighborhood 1          9         3945       82458
1  Neighborhood 2          5         5820       81444
2  Neighborhood 3          6         5463       94137
3  Neighborhood 4          5         5279       75986
4  Neighborhood 5          5         5338       69829

In [2]:
df.isnull().sum()

neighborhood    0
num_parks       0
pop_density     0
avg_income      0
dtype: int64

In [19]:
df['pop_category'] = pd.qcut(df['pop_density'], q=3, labels=['Low', 'Medium', 'High'])
df['pop_category'].head()

0       Low
1      High
2      High
3    Medium
4      High
Name: pop_category, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [18]:
df['pop_category'].value_counts()

pop_category
Low       34
High      34
Medium    32
Name: count, dtype: int64

In [15]:
#turn it into category for chi-square test
df['income_category'] = pd.qcut(df['avg_income'], q=3, labels=['Low', 'Medium', 'High'])
df['income_category'].head()

0    Medium
1    Medium
2      High
3    Medium
4       Low
Name: income_category, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [21]:
df['income_category'].value_counts()

income_category
Low       34
Medium    33
High      33
Name: count, dtype: int64

In [14]:
df.head()

     neighborhood  num_parks  pop_density  avg_income
0  Neighborhood 1          9         3945       82458
1  Neighborhood 2          5         5820       81444
2  Neighborhood 3          6         5463       94137
3  Neighborhood 4          5         5279       75986
4  Neighborhood 5          5         5338       69829

In [26]:
#turn it into category for chi-square test
df['parks_category'] = pd.qcut(df['num_parks'], q=3, labels=['Low', 'Medium', 'High'])
df['parks_category'].head()

0      High
1    Medium
2      High
3    Medium
4    Medium
Name: parks_category, dtype: category
Categories (3, object): ['Low' < 'Medium' < 'High']

In [24]:
df['parks_category'].value_counts()

parks_category
Low       48
High      34
Medium    18
Name: count, dtype: int64

## Chi-square Test

In [30]:
#contingency table: two categorical variables
#chi square test 1: population density and number of parks
contingency_pop = pd.crosstab(df['pop_category'], df['parks_category'])
contingency_pop

parks_category  Low  Medium  High
pop_category
Low              14       7    13
Medium           19       4     9
High             15       7    12

In [31]:
chi2, p, dof, expected = chi2_contingency(contingency_pop)

print("Chi2:", chi2)
print("p-value:", p)

#p-value = 0.6248 > 0.05: this indicates there's no statistically significant relationship between population density and number of parks

Chi2: 2.6109999759707807
p-value: 0.6248757677946034

In [32]:
#chi square test 2: average income and number of parks
contingency_income = pd.crosstab(df['income_category'], df['parks_category'])
contingency_income

parks_category   Low  Medium  High
income_category
Low               18       9     7
Medium            14       6    13
High              16       3    14

In [33]:
chi2_income, p_income, dof, expected = chi2_contingency(contingency_income)

print("Chi2:", chi2_income)
print("p-value:", p_income)

#p-value = 0.2014 > 0.05: this indicates there's no statistically significant relationship between average income and number of parks

Chi2: 5.969295026388452
p-value: 0.20145310418284063

In [ ]:
# neither population density nor average income appears to significantly influence park distribution

## Correlation Analysis

In [35]:
#correlation analysis 1: population density and number of parks
corr_pop, p_pop_corr = pearsonr(df['num_parks'], df['pop_density'])

print("Correlation (parks vs pop_density):", corr_pop)
print("p-value:", p_pop_corr)

#There is no meaningful relationship between population density and number of parks.

Correlation (parks vs pop_density): -0.030414201604427052
p-value: 0.7638814470642239

In [38]:
#correlation analysis 2: average income and number of parks
corr_income, p_income_corr = pearsonr(df['num_parks'], df['avg_income'])

print("Correlation (parks vs income):", corr_income)
print("p-value:", p_income_corr)

#There is a weak positive correlation between average income and number of parks, but it is not statistically significant.

Correlation (parks vs income): 0.1445707431996942
p-value: 0.15126364023202615

## Final Verdict

Based on the analysis, park distribution does not show a statistically significant relationship with either population density or average income.

This suggests that current park placement may not be strategically aligned with community needs.

It is recommended that city planners consider additional factors such as:
- Accessibility
- Community demand
- Environmental conditions
- Urban development goals

Ensuring equitable access to green spaces should remain a priority.